font_family     JetBrainsMono Nerd Font Mono
font_size 12.0
backgraund_opacity 0.98

cursor_trail 1

window_margin 22

confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME
