# Foot - Purple colors
[cursor]
color=0a0410 b44dff

[colors]
alpha=0.85
foreground=c77dff
background=0a0410

regular0=1e1626
regular1=9333ea
regular2=b44dff
regular3=ff6ac1
regular4=6b21a8
regular5=c77dff
regular6=61d6ff
regular7=e3c8ff

bright0=3a2f4a
bright1=a855f7
bright2=c77dff
bright3=ff8ed1
bright4=7c3aed
bright5=d8a5ff
bright6=8ee3ff
bright7=f1e3ff

selection-foreground=f1e3ff
selection-background=2a0a4a
urls=61d6ff
