# Purple - sway client colors
# class                 border  bground text    indicator child_border
client.focused          #b44dff #b44dff #000000 #e3c8ff   #b44dff
client.focused_inactive #331d57 #1c1030 #b44dff #331d57   #331d57
client.unfocused        #2a0a4a #0a0410 #6b21a8 #2a0a4a   #2a0a4a
client.urgent           #ff6ac1 #ff6ac1 #000000 #ff6ac1   #ff6ac1

# SwayFX shadow tint
shadow_color #B44DFF40
