# Purple - sway client colors
# class                 border  bground text    indicator child_border
client.focused          #5c2a99 #5c2a99 #ffffff #47246b   #5c2a99
client.focused_inactive #d0bce8 #e6dcf2 #5c2a99 #d0bce8   #d0bce8
client.unfocused        #5a4a7a #f4f0f8 #4a1a75 #5a4a7a   #5a4a7a
client.urgent           #a81a6b #a81a6b #ffffff #a81a6b   #a81a6b

