# Matrix - sway client colors
# class                 border  bground text    indicator child_border
client.focused          #0d7a2c #0d7a2c #ffffff #2c6e37   #0d7a2c
client.focused_inactive #cde3d2 #e2efe6 #0d7a2c #cde3d2   #cde3d2
client.unfocused        #4a7a4a #f2f5f3 #0f6b23 #4a7a4a   #4a7a4a
client.urgent           #4a8a1d #4a8a1d #ffffff #4a8a1d   #4a8a1d

