# Example - sway client colors (teal starter palette - edit me!)
# class                 border  bground text    indicator child_border
client.focused          #00e5c7 #00e5c7 #000000 #b3fff4   #00e5c7
client.focused_inactive #14443b #0a2620 #00e5c7 #14443b   #14443b
client.unfocused        #00332c #02100e #00806e #00332c   #00332c
client.urgent           #ffd166 #ffd166 #000000 #ffd166   #ffd166

# SwayFX shadow tint
shadow_color #00E5C740
