# Foot - Matrix colors
[cursor]
color=0d0208 00ff41

[colors]
alpha=0.85
foreground=00ff41
background=0d0208

regular0=1a221a
regular1=00b32c
regular2=00ff41
regular3=aaff66
regular4=008f11
regular5=00d95f
regular6=35ffa9
regular7=baffc4

bright0=2f3f2f
bright1=00d935
bright2=4dff7a
bright3=ccffa3
bright4=00b316
bright5=35ff8d
bright6=6fffc4
bright7=d9ffe0

selection-foreground=d9ffe0
selection-background=003b00
urls=35ffa9
