# Matrix - sway client colors
# class                 border  bground text    indicator child_border
client.focused          #00ff41 #00ff41 #000000 #baffc4   #00ff41
client.focused_inactive #1e3b1e #0f1f0f #00ff41 #1e3b1e   #1e3b1e
client.unfocused        #003b00 #0d0208 #008f11 #003b00   #003b00
client.urgent           #aaff66 #aaff66 #000000 #aaff66   #aaff66

# SwayFX shadow tint
shadow_color #00FF4140
